services:
  localstack:
    image: localstack/localstack:3
    container_name: pfa-localstack-outils
    environment:
      SERVICES: s3
    ports:
      - "4566:4566"
    networks:
      - pfa-outils

  terraform:
    image: hashicorp/terraform:1.9
    working_dir: /work/infrastructure/terraform
    volumes:
      - ..:/work
      - ../.kube:/root/.kube:ro
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-west-1
      TF_VAR_localstack_endpoint: http://localstack:4566
      KUBECONFIG: /root/.kube/config
    networks:
      - pfa-outils
    depends_on:
      - localstack

  kubectl:
    image: bitnami/kubectl:latest
    volumes:
      - ../.kube:/root/.kube:ro
    environment:
      KUBECONFIG: /root/.kube/config
    networks:
      - pfa-outils

  helm:
    image: alpine/helm:3.16
    volumes:
      - ..:/work
      - ../.kube:/root/.kube:ro
    environment:
      KUBECONFIG: /root/.kube/config
    working_dir: /work
    networks:
      - pfa-outils

networks:
  pfa-outils:
    driver: bridge
