apiVersion: v1
kind: Secret
metadata:
  name: pfa-stock-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_JWT: {{ .Values.secretJwt | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}
