apiVersion: v1
kind: Secret
metadata:
  name: pfa-stock-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SECRET_JWT: {{ .Values.secretJwt | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
