apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.imageWeb.repository }}:{{ .Values.imageWeb.tag }}"
          imagePullPolicy: {{ .Values.imageWeb.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
