#!/usr/bin/env bash
cd "$(dirname "$0")/.."

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           PFA GESTION DE STOCK — ACCÈS & IDENTIFIANTS           ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Mode: DÉVELOPPEMENT (Docker Compose)"
echo ""
echo "  Application (UI)     http://localhost:3000"
echo "  API REST             http://localhost:8000"
echo "  Documentation API    http://localhost:8000/docs"
echo "  Métriques Prometheus http://localhost:8000/metrics"
echo "  PostgreSQL           localhost:5432 (stock / stock / stock_db)"
echo ""
echo "── Production (après déploiement VPS) ──"
echo "  Application          https://pfa.elyes.dev"
echo "  API                  https://api.pfa.elyes.dev"
echo "  Grafana              https://grafana.pfa.elyes.dev"
echo "  pgAdmin              https://pgadmin.pfa.elyes.dev"
echo "  Dashboard K8s        https://dashboard.pfa.elyes.dev"
echo ""
echo "── Comptes application ──"
echo "  Admin      admin@stock.tn          /  Admin123!"
echo "  Opérateur  operateur@stock.tn      /  Operateur123!"
echo ""
echo "── Arrêt ──"
echo "  make destroy"
echo ""
