#!/usr/bin/env bash
cd "$(dirname "$0")/.."

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           PFA GESTION DE STOCK — ACCÈS & IDENTIFIANTS           ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Mode: DÉVELOPPEMENT (Docker Compose)"
echo ""
echo "  Application (UI)     http://localhost:3000"
echo "  API REST             http://localhost:8000"
echo "  Documentation API    http://localhost:8000/docs"
echo "  Métriques Prometheus http://localhost:8000/metrics"
echo "  PostgreSQL           localhost:5432 (stock / stock / stock_db)"
echo "  Adminer (DB UI)      http://localhost:8080"
echo "    Système: PostgreSQL · Serveur: postgres · User: stock · Pass: stock · DB: stock_db"
echo ""
echo "── Kubernetes local (minikube) ──"
echo "  make cluster         minikube + Grafana + pgAdmin + dashboard K8s + app"
echo "  make cluster-down    Arrête / supprime le cluster"
echo "  /etc/hosts (après make cluster, adapter l'IP) :"
echo "    <minikube ip>  pfa.test api.pfa.test grafana.test pgadmin.test"
echo ""
echo "── Production optionnelle (VPS k3s dédié) ──"
echo "  docs/vps-setup.md    Terraform + deploy.yml manuel (hors soutenance)"
echo ""
echo "── Comptes application ──"
echo "  Admin      admin@stock.tn          /  Admin123!"
echo "  Opérateur  operateur@stock.tn      /  Operateur123!"
echo ""
echo "── Arrêt ──"
echo "  make destroy"
echo ""
